name: CI
on: [push]
jobs:
  check_formatting:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install poetry and dependencies
        run: |
          curl -sLL https://install.python-poetry.org | python3 -
          poetry install --no-interaction --no-ansi --no-root
      - name: check formatting
        run: |
          poetry run black --check .

  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install poetry and dependencies
        run: |
          curl -sLL https://install.python-poetry.org | python3 -
          poetry install --no-interaction --no-ansi --no-root
      - name: run unit tests
        run: |
          poetry run pytest
